### ISSUE TITLE
Failed to install wildgaussians with conda backend doe to cuda version mismatch

### ISSUE THREAD

**Issue by Sugar55888** [nerfbaselines/nerfbaselines#28] opened 2024-09-23 14:53 UTC
When I directly use the command `nerfbaselines train --method wild-gaussians --data ./data/drone --backend conda` to run wildgaussian, there will be a mismatch between the pytorch version and the cuda version, which cause the following error:

Processing ./submodules/simple-knn
  Preparing metadata (setup.py) ... done
Obtaining file:///home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/src/wild-gaussians/submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simple_knn
  Building wheel for simple_knn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/src/wild-gaussians/submodules/simple-knn/setup.py", line 21, in <module>
          setup(
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/wheel/_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.6) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple_knn
  Running setup.py clean for simple_knn
Failed to build simple_knn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (simple_knn)
Traceback (most recent call last):
  File "/mnt/sdb1/user/anaconda3/envs/nerfbaseline/bin/nerfbaselines", line 8, in <module>
    sys.exit(main())
  File "/mnt/sdb1/user/anaconda3/envs/nerfbaseline/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/sdb1/user/anaconda3/envs/nerfbaseline/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/mnt/sdb1/user/anaconda3/envs/nerfbaseline/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/sdb2/user/code/nerfbaselines/nerfbaselines/cli/_common.py", line 499, in invoke
    return super().invoke(ctx)
  File "/mnt/sdb1/user/anaconda3/envs/nerfbaseline/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/sdb1/user/anaconda3/envs/nerfbaseline/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/sdb2/user/code/nerfbaselines/nerfbaselines/cli/_common.py", line 440, in wrapped
    raise e
  File "/mnt/sdb2/user/code/nerfbaselines/nerfbaselines/cli/_common.py", line 433, in wrapped
    return fn(*args, **kwargs)
  File "/mnt/sdb2/user/code/nerfbaselines/nerfbaselines/cli/_train.py", line 93, in train_command
    method_cls = stack.enter_context(build_method_class(method_spec, backend_name))
  File "/mnt/sdb1/user/anaconda3/envs/nerfbaseline/lib/python3.8/contextlib.py", line 425, in enter_context
    result = _cm_type.__enter__(cm)
  File "/mnt/sdb1/user/anaconda3/envs/nerfbaseline/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/mnt/sdb2/user/code/nerfbaselines/nerfbaselines/_method_utils.py", line 87, in build_method_class
    backend_impl.install()
  File "/mnt/sdb2/user/code/nerfbaselines/nerfbaselines/backends/_conda.py", line 196, in install
    subprocess.check_call(["bash", "-l", "-c", conda_get_install_script(self._spec, package_path=package_path)])
  File "/mnt/sdb1/user/anaconda3/envs/nerfbaseline/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '-l', '-c', 'set -eo pipefail\n\n# Clear old environments\nwas_message=0\nif [ -d /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians ]; then\n    for hash in $(ls -1 /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians); do\n        if [ "$hash" != 96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1 ]; then\n            if [ "$was_message" -eq 0 ]; then\n                echo "Clearing old environments"\n                was_message=1\n            fi\n            echo "   Removing old environment $hash"\n            rm -rf /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians"/$hash"\n        fi\n    done\nfi\n\n# Create new environment\neval "$(conda shell.bash hook)"\nmkdir -p /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1\nif [ ! -e /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.ack.txt ]; then\nif [ -e /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock/pid ] && [ ! -e /proc/$(cat /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock/pid) ] && [ "$(cat /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock/nodename)" = "$(hostname)" ]; then\n    echo "Removing stale lock file /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock (no process running)"\n    rm -rf /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock\nfi\nif ! mkdir /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock 2>/dev/null; then\n    # Wait for the other process to write PID\n    sleep 1\n    pid=$(cat /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock/pid)\n    nodename=$(cat /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock/nodename)\n    echo "Creating new is already running (lock: /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock,pid:$pid,nodename:$nodename)" >&2\n    echo "Waiting for the other process to finish" >&2\n    while [ -e /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock ] || [ -e /proc/$pid ]; do\n        sleep 1\n    done\n    if [ ! -e /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.ack.txt ]; then\n        echo "The other process failed to build the environment." >&2\n        exit 1\n    else\n        echo "The other process finished building the environment." >&2\n        exit 0\n    fi\nfi\necho $(hostname) > /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock/nodename\necho $$ > /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock/pid\ntrap "rm -rf /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.lock" EXIT\necho "Creating new environment /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians"\n\nrm -rf /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians\nconda deactivate\nconda create --prefix /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians -y -c conda-forge --override-channels python=3.11\nconda activate /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians\necho -e \'channels:\n  - conda-forge\n\' > /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/.condarc\nconda install -y pip conda-build ffmpeg\npip install --upgrade pip setuptools\nmkdir -p /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/nb-sources\nmkdir -p /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/src\ncd /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/src\n\ngit clone https://github.com/jkulhanek/wild-gaussians.git\ncd wild-gaussians\ngit checkout 481e46b478fc259e991bf4873b139c0ad33613ec\nconda install -y --override-channels -c nvidia/label/cuda-11.8.0 cuda-toolkit\nif [ "$NERFBASELINES_DOCKER_BUILD" != "1" ]; then\nconda install -y gcc_linux-64=11 gxx_linux-64=11 make=4.3 cmake=3.28.3 -c conda-forge\nfi\npip install --upgrade pip\npip install \'numpy<2.0.0\' -r requirements.txt\nLIBRARY_PATH="$CONDA_PREFIX/lib/stubs" pip install -e ./submodules/diff-gaussian-rasterization ./submodules/simple-knn\npip install -e .\npip install opencv-python-headless\n\nfunction nb-post-install () {\nif [ "$NERFBASELINES_DOCKER_BUILD" = "1" ]; then\n# Reduce size of the environment by removing unused files\nfind "$CONDA_PREFIX" -name \'*.a\' -delete\nfind "$CONDA_PREFIX" -type d -name \'nsight*\' -exec rm -r {} +\n# Replace all libs under $CONDA_PREFIX/lib with symlinks to pkgs/cuda-toolkit/targets/x86_64-linux/lib\nfor lib in "$CONDA_PREFIX"/lib/*.so*; do \n    if [ ! -f "$lib" ] || [ -L "$lib" ]; then continue; fi;\n    lib="${lib%.so*}.so";libname=$(basename "$lib");\n    tgt="$CONDA_PREFIX/pkgs/cuda-toolkit/targets/x86_64-linux/lib/$libname"\n    if [ -f "$tgt" ]; then echo "Deleting $lib"; rm "$lib"*; for tgtlib in "$tgt"*; do ln -s "$tgtlib" "$(dirname "$lib")"; done; fi;\ndone\nfi\n}\n\npip install \'Pillow>=8.2.0\' \'click>=8.0.0\' \'gdown>=4.7.1\' \'importlib-metadata>=6.0.0\' \'matplotlib>=3.4.2\' \'mediapy>=1.1.2\' \'numpy<2.0.0,>=1.19.5\' \'opencv-python>=4.6.0\' \'requests>=2.25.1\' \'scipy\' \'splines>=0.3.1\' \'tensorboard>=2.5.0\' \'tqdm>=4.61.1\' \'typing-extensions>=4.4.0\' \'viser<0.2.0\' \'wandb>=0.13.3\'\n\n# Prepare default nerfbaselines\nsite_packages="$(python -c \'import site; print(site.getsitepackages()[0])\')"\nif [[ "$site_packages" != "$CONDA_PREFIX/"* ]]; then\n    echo "ERROR: site-packages is not in the conda environment"; exit 1;\nfi\nln -s /mnt/sdb2/user/code/nerfbaselines/nerfbaselines "$site_packages"\n\n# Add nerfbaselines to the path\nif ! nerfbaselines >/dev/null 2>&1; then\n    echo \'#!/usr/bin/env python3\nfrom nerfbaselines.__main__ import main; main()\'>"$CONDA_PREFIX/bin/nerfbaselines"\n    chmod +x "$CONDA_PREFIX/bin/nerfbaselines"\nfi\n\necho \'#!/bin/bash\' > /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/.activate.sh\necho \'eval "$(conda shell.bash hook)"\' >> /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/.activate.sh\necho \'conda activate /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians;export NERFBASELINES_BACKEND=python;export NERFBASELINES_ALLOWED_METHODS=""\' >> /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/.activate.sh\necho \'exec "$@"\' >> /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/.activate.sh\nchmod +x /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians/.activate.sh\n# If function nb-post-install is declared, run it\nif declare -f nb-post-install >/dev/null; then\n    nb-post-install || exit 1\nfi\ntouch /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.ack.txt\necho "0" > /home/user/.cache/nerfbaselines/conda-envs/wild-gaussians/96f523e19958a2942a6bf095d3a3cb45dd3e80e1e01aa0c32c7b94ef2f2790d1/wild-gaussians.ack.txt\nfi\n']' returned non-zero exit status 1.

**Comment by jkulhanek** [comment] 2024-09-23 19:10
Hi, thanks for the traceback!
I've done some fixes, can you please try with the current `main`?
```
pip install git+https://github.com/nerfbaselines/nerfbaselines.git
```

**Comment by Sugar55888** [comment] 2024-09-24 02:13
@jkulhanek Hi, I install the lastest nerfbaseline following `pip install git+https://github.com/nerfbaselines/nerfbaselines.git`. But it meets the same problem. It is weird.

**Comment by jkulhanek** [comment] 2024-09-24 04:48
Can you send me your os version and environment variables? `env | grep cuda`?

**Comment by Sugar55888** [comment] 2024-09-24 05:14
@jkulhanek Here is my environment variables:
```
LIBRARY_PATH=:/usr/local/cuda-11.8/lib64
LD_LIBRARY_PATH=/usr/local/opencv-3.4.16/lib:/usr/local/cuda-11.8/lib64/
PATH=/home/user/anaconda3/bin:/home/user/anaconda3/condabin:/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-11.8/bin
```
I run it on ubuntu 20.04 and cuda 11.8.

**Comment by jkulhanek** [comment] 2024-09-24 05:20
I see, can you please send the full output of the command?

**Comment by Sugar55888** [comment] 2024-09-24 05:32
@jkulhanek It is full output of the command. And I can sucessfully run wild-gaussian following the origin reposity；
```
git clone git@github.com:jkulhanek/wild-gaussians.git
cd wild-gaussians

conda create -y -n wg python=3.11
conda activate wg
conda install -y --override-channels -c nvidia/label/cuda-11.8.0 cuda-toolkit
conda env config vars set NERFBASELINES_BACKEND=python
pip install --upgrade pip
pip install -r requirements.txt
pip install nerfbaselines>=1.2.0
pip install -e ./submodules/diff-gaussian-rasterization ./submodules/simple-knn
pip install -e .
```
So I think there is no problem with my cuda environment settings. But when I use the nerfbaseline command to create wild-gaussian, the above error occurs, which is strange.

**Comment by jkulhanek** [comment] 2024-09-24 05:41
I don’t think the command you’ve sent is the full output of ‘nerfbaselines train’. At the begining it should say something about a new emvironment being created and afterwards you should see it installing torch and cuda toolkit. This would be helpful for me because perhaps it tries to install a wrong version of cuda or torch for some reason. Perhaps you can capture the output (stdout, stderr) to a file and send it?  Thank you very much for your kind help.

**Comment by Sugar55888** [comment] 2024-09-24 06:04
@jkulhanek Sorry, I mistakenly thought you meant the full output of env | grep. This is the full output text of the nerfbaselines train --method wild-gaussians --data ./data/drone --backend conda command.
[1.txt](https://github.com/user-attachments/files/17108913/1.txt)

**Comment by jkulhanek** [comment] 2024-09-24 07:11
@Sugar55888 thank you! by inspecting your output I saw cuda 12.6 was indeed installed. Can you try with the newest `main` version. I believe it will fix the issue now. If not, can you please post the output again. Sorry to bother you, but in my case, the installation worked fine even before so I cannot reproduce the issue locally.

**Comment by Sugar55888** [comment] 2024-09-24 07:30
@jkulhanek Thank you! I have scuccessfully run the wild-gaussian using nerfbaseline now.

**Comment by jkulhanek** [comment] 2024-09-24 07:34
Great! glad it helped. The fixed install script will be part of the next nerfbaselines release in a few days.

**Closed by jkulhanek** 2024-09-24 07:34 UTC
