### ISSUE TITLE
Memory problems with custom dataset

### ISSUE THREAD

**Issue by Mikey-E** [nerfbaselines/nerfbaselines#29] opened 2024-09-24 06:53 UTC
For gaussian-opacity-fields it appears that grads and grads_abs may not be getting cleared correctly between calls of densify_and_prune(). They seem to double in size each time, eventually leading to out of memory errors. As such, simply changing memory parameters or environment variables does little to help. What is the best way to manage this size during training?

**Comment by jkulhanek** [comment] 2024-09-24 07:03
Hi, thank you for your question. Grads and grads_abs doubling in size means that the number of gaussians doubles each densify step; am I right? From my understanding, the issue is caused by GOF, not by nerfbaselines (it calls GOF code internally). If that is the case, asking at https://github.com/autonomousvision/gaussian-opacity-fields might be better. I believe the issue can be the scale of your scene. I would recommend trying to adjust the densification and pruning thresholds. Btw, do you have the same issue with gaussian-splatting or mip-splatting?

**Comment by Mikey-E** [comment] 2024-09-24 19:50
We don't seem to have it with gaussian-splatting or mip-splatting. I will ask at gaussian-opacity-fields.

**Comment by jkulhanek** [comment] 2024-10-10 08:23
Closing the issue as it seems to be the issue with GOF rather then nerfbaselines.

**Closed by jkulhanek** 2024-10-10 08:23 UTC
